CREATE TABLE IF NOT EXISTS SIMULATION_DAY(
    ID BIGINT AUTO_INCREMENT,
    DEATH_PEOPLE BIGINT,
    HEALTHY_PEOPLE BIGINT,
    IMMUNE_PEOPLE BIGINT,
    INFECTED_PEOPLE BIGINT,
    SIMULATION_DAY BIGINT,
    SIMULATION_ID BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (SIMULATION_ID) REFERENCES SIMULATION(ID)
);

CREATE TABLE IF NOT EXISTS SIMULATION(
    ID BIGINT AUTO_INCREMENT,
    DAYS_OF_SIMULATION BIGINT,
    DAYS_TO_DEATH BIGINT,
    DAYS_TO_RECOVER BIGINT,
    INIT_INFECTED BIGINT,
    MORTALITY BIGINT,
    NAME VARCHAR(255),
    POPULATION BIGINT,
    REPRODUCTION BIGINT
);